### ISSUE TITLE
Remove transparency from icons

### ISSUE THREAD

**Issue by ThaUnknown** [ThaUnknown/pwa-haven#8]
some OS's and &| browsers don't fully support transparent icons for shortcuts, like some android launchers or brave mobile, so lets add some dark background to all icons.

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/pwa-haven/commit/5085e226b38693e4d0653823b74f028f6a90137c

**Comment by myhiy1** [comment]
can u make icons rounded atleast then.

**Comment by ThaUnknown** [comment]
> can u make icons rounded atleast then.

https://github.com/ThaUnknown/pwa-haven/commit/260f14c6db869b0769bebf0abe8d9e8fa0bdc16b
